---

- name: Spotify | Add key
  apt_key: keyserver=keyserver.ubuntu.com id=94558F59

- name: Spotify | Add repository
  apt_repository: repo='deb http://repository.spotify.com stable non-free' state=present update_cache=yes

- name: Spotify | Install spotify
  apt: name=spotify-client state=latest
