---

- name: Spotify | Add key
  apt_key: keyserver=keyserver.ubuntu.com id=94558F59

- name: Spotify | Add repository
  apt_repository: repo='deb http://repository.spotify.com stable non-free'

- name: Spotify | Install spotify
  apt: name=spotify-client update_cache=yes state=latest
